# Generated by Django 3.0.8 on 2020-10-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_auto_20201024_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receipt',
        ),
        migrations.AddField(
            model_name='transaction',
            name='reciept',
            field=models.CharField(default='null', max_length=5000),
            preserve_default=False,
        ),
    ]
