# Generated by Django 3.0.8 on 2020-10-25 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_auto_20201025_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='reciept',
            new_name='receipt',
        ),
    ]
