# Generated by Django 3.0.8 on 2020-11-07 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_auto_20201026_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-id']},
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('monthly_exp_amt', models.FloatField()),
                ('category_bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_cat', to='buckets.Bucket')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
