# Generated by Django 3.0.8 on 2020-10-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0004_auto_20201025_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='is_active',
            field=models.BooleanField(default=1),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='min_amt',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='parent_bucket',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
