# Generated by Django 3.0.8 on 2020-11-07 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0006_auto_20201107_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='category_bucket',
            new_name='bucket',
        ),
    ]
