# Generated by Django 3.0.8 on 2020-10-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0006_auto_20201025_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
