# Generated by Django 3.0.8 on 2020-11-07 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0007_auto_20201107_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='buckets.Expense'),
        ),
    ]
