# Generated by Django 3.0.8 on 2020-10-25 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0007_auto_20201025_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='parent_bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buckets.Bucket'),
        ),
    ]
