# Generated by Django 3.0.8 on 2020-11-07 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0008_bucket_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='bucket',
        ),
    ]
