# Generated by Django 3.0.8 on 2020-11-07 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0009_remove_expense_bucket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='expense',
        ),
        migrations.AddField(
            model_name='expense',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='buckets.Bucket'),
        ),
    ]
