# Generated by Django 3.0.8 on 2020-10-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0009_auto_20201025_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
