# Generated by Django 3.0.8 on 2020-10-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0010_auto_20201025_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
