# Generated by Django 3.0.8 on 2020-10-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0011_auto_20201025_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
