# Generated by Django 3.0.8 on 2020-11-07 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0011_auto_20201107_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='min_amt',
        ),
    ]
