# Generated by Django 3.0.8 on 2020-10-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0013_auto_20201025_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='parent',
            new_name='parent_bucket',
        ),
    ]
