# Generated by Django 3.0.8 on 2020-10-25 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0018_auto_20201025_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='parent_bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='buckets.Bucket'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='income',
            field=models.IntegerField(),
        ),
    ]
