# Generated by Django 3.0.8 on 2020-10-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0019_auto_20201025_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='income',
            field=models.FloatField(),
        ),
    ]
